import { Worker } from 'bullmq';
console.log('Embedding worker started 🚀');
import Redis from 'ioredis';
import config from '../core/config/env.config.js';
import { Item } from '../core/database/models/index.js';

const redisConnection = new Redis({
  host: config.redis.host,
  port: config.redis.port,
  password: config.redis.password || undefined,
  maxRetriesPerRequest: null,
});

const embeddingWorker = new Worker(
  config.workers.embeddingQueue,
  async (job) => {
    try {
      const { itemId } = job.data;
      const item = await Item.findById(itemId);
      if (!item) throw new Error('Item not found');

      // Generate text content for embedding
      const textContent = `${item.title} ${item.excerpt || ''} ${item.content || ''}`.substring(0, 5000);
      
      const { generateEmbedding } = await import('../utils/embedding.util.js');
      const vector = await generateEmbedding(textContent);

      if (vector) {
        const { Embedding } = await import('../core/database/models/index.js');
        await Embedding.findOneAndUpdate(
          { item: itemId },
          {
            item: itemId,
            user: item.user,
            vector,
            textContent,
            model: config.gemini.embeddingModel || 'gemini-embedding-001',
            dimensions: config.gemini.embeddingDimensions || 768,
          },
          { upsert: true, new: true }
        );
        console.log(`Embedding generated and saved for item ${itemId}`);

        // Generate Relations
        const { Relation } = await import('../core/database/models/index.js');
        const { cosineSimilarity } = await import('../utils/embedding.util.js');
        
        const otherEmbeddings = await Embedding.find({ 
          user: item.user, 
          item: { $ne: itemId } 
        });

        for (const other of otherEmbeddings) {
          const similarity = cosineSimilarity(vector, other.vector);
          if (similarity > 0.8) {
             await Relation.findOneAndUpdate(
               { 
                 user: item.user, 
                 sourceItem: itemId, 
                 targetItem: other.item 
               },
               { 
                 relationType: 'similar', 
                 strength: similarity,
                 isAutoGenerated: true,
                 metadata: { similarityScore: similarity, reason: 'High semantic similarity' }
               },
               { upsert: true }
             );
          }
        }
      }

      return { success: true, itemId };
    } catch (error) {
      console.error('Embedding worker error:', error.message);
      return { success: false, error: error.message };
    }
  },
  {
    connection: redisConnection,
    concurrency: 3,
  }
);

embeddingWorker.on('completed', (job) => {
  console.log(`Embedding job ${job.id} done`);
});

embeddingWorker.on('failed', (job, err) => {
  console.log(`Embedding job ${job?.id} failed: ${err.message}`);
});

export default embeddingWorker;