import mongoose from 'mongoose';

const relationSchema = new mongoose.Schema(
  {
    user: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
      index: true,
    },
    sourceItem: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Item',
      required: true,
      index: true,
    },
    targetItem: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Item',
      required: true,
      index: true,
    },
    relationType: {
      type: String,
      enum: ['similar', 'related', 'reference', 'inspired_by', 'custom'],
      default: 'related',
    },
    strength: {
      type: Number,
      min: 0,
      max: 1,
      default: 0.5,
    },
    isAutoGenerated: {
      type: Boolean,
      default: true,
    },
    metadata: {
      sharedTags: [String],
      sharedTopics: [String],
      similarityScore: Number,
      reason: String,
    },
  },
  {
    timestamps: true,
  }
);

relationSchema.index({ user: 1, sourceItem: 1 });
relationSchema.index({ user: 1, targetItem: 1 });
relationSchema.index({ user: 1, sourceItem: 1, targetItem: 1 }, { unique: true });

const Relation = mongoose.model('Relation', relationSchema);

export default Relation;
